spring:
  application:
    name: gestion-empleados
  config:
    import: optional:classpath:application-secret.yml
  data:
    mongodb:
      database: empleados-db
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
server:
  port: 8080

logging:
  level:
    com.microservicios.empleados: INFO
    org.springframework.data.mongodb: INFO
